version: 2.1
jobs:
  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
  build_android:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: echo ${GOOGLE_SERVICES} | base64 --decode > ~/project/android/app/google-services.json
      - run: flutter -v build apk
      - store_artifacts:
          path: ~/project/build/app/outputs
      - store_artifacts:
          path: ~/project/build/app/reports
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_android:
          requires:
            - test